config/routes.rb
Blog::Application.routes.draw do
  resources :users do
    resources :saved_posts, only: [:index]
    resources :friendships, only: [:index]
  end
  resources :blog_posts do
    resources :comments
  end
  
  resources :saved_posts, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root :to => 'static_pages#home'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  match '/save/:blogpost_id', to: 'saved_posts#create', as: 'fav_blogpost'
  match '/delete/:blogpost_id', to: 'saved_posts#destroy', as: 'unfav_blogpost'
  match '/add_friend/:user_id', to: 'friendships#create', as: 'add_friend'
  match '/rm_friend/:user_id', to: 'friendships#destroy', as: 'remove_friend'
  match '/users/:user_id/confirm/:confirmation_code', to: 'users#confirmation', as: 'confirmation'
  match '/confirm_friendship/:friendship_id/:confirmation_code', to: 'friendships#confirmation', as: 'f_confirmation'

end

app/views/comment_partials/_entry_comments.html.erb
<% @comments.each do |comment| %>
    <div class="comment">
        <p><%= comment.content %></p>
        <p>
        	<% unless comment.user.image_url.nil? %>
        		<%= image_tag comment.user.image_url(:thumb).to_s, class: "comment_image" %>
            <% else %>
            	<%= image_tag("thumb_default_avatar.jpg", alt: "Avatar", class: "comment_image" ) %>
            <% end %>
            
	        <%="#{time_ago_in_words(comment.created_at)}"%> ago  by
	        <% if current_user.admin? %>
	            <%= link_to comment.user.full_name, comment.user%>
	        <% else %>
	            <%= comment.user.full_name %>
	        <% end %>
	        <% if !current_user?(comment.user) %>
	            <span class="comment_friends">
	                <% if current_user.friends?(comment.user)%>
	                    <%= link_to 'Remove from friends', remove_friend_path(comment.user),
	                                                        method: :delete,
	                                                        data: { confirm: "You sure?" },
	                                                        class: "icon-ban-circle" %>
	                <% else %>
	                    <%= link_to 'Add to friends', add_friend_path(comment.user), class: "icon-plus" %>
	                <% end %>
	            </span>
	        <% end %>
	        <br />
	        <% if signed_in? %>
	            <% if comment_by_user?(comment.user) %>
	                <%= link_to "Edit",edit_blog_post_comment_path(@blogpost, comment), class: "icon-edit" %>
	            <% end %>
	            
	            <% if comment_by_user?(comment.user) || current_user.admin? %>
	                    <%= link_to "Delete", blog_post_comment_path(@blogpost, comment),
	                                                 method: :delete,
	                                                 data: { confirm: "Are you sure?"}, 
	                                                 class: "icon-trash" %>
	            <% end %>
	        <% end %>
        </p>
    </div>
<% end %>

<br />
<%= button_to "Create a new comment", new_blog_post_comment_path(@blogpost),
                                      class: "new_comment",
                                      method: "get" %>

app/views/comment_partials/_friends.html.erb
        <% if !current_user?(comment.user) %>
            <span class="comment_friends">
                <% unless current_user.friends?(comment.user)%>
                    <%= link_to 'Remove from friends', remove_friend_path(comment.user),
                                                        method: :delete,
                                                        data: { confirm: "You sure?" } %>
                <% else %>
                    <%= link_to 'Add to friends', add_friend_path(comment.user) %>
                <% end %>
            </span>
        <% end %>