config/routes.rb
Blog::Application.routes.draw do
  resources :users do
    resources :saved_posts, only: [:index]
    resources :friendships, only: [:index]
  end
  resources :blog_posts do
    resources :comments
  end
  
  resources :saved_posts, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root :to => 'static_pages#home'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  match '/save/:blogpost_id', to: 'saved_posts#create', as: 'fav_blogpost'
  match '/delete/:blogpost_id', to: 'saved_posts#destroy', as: 'unfav_blogpost'
  match '/add_friend/:user_id', to: 'friendships#create', as: 'add_friend'
  match '/rm_friend/:user_id', to: 'friendships#destroy', as: 'remove_friend'
  match '/users/:user_id/confirm/:confirmation_code', to: 'users#confirmation', as: 'confirmation'
  match '/confirm_friendship/:friendship_id/:confirmation_code', to: 'friendships#confirmation', as: 'f_confirmation'

end

app/views/notifier/friend_request.text.erb
Hello <%= @other_user.full_name %>,

<%= @user.full_name %> wants to be friends with you and sended you a friend request.
To confirm <%= @user.full_name %> as a friend click the following link:
<%= f_confirmation_url(@friendship.id, @friendship.confirmation_code, :host => "localhost:3000") %>

To decline the request click this link:
PLACEHOLDER

Sincerly,
The Sample Blog Administration

app/views/notifier/signed_up.text.erb
Dear <%= @user.first_name %> <%= @user.last_name %>,

you successfully singed up at the Sample Blog.

To confirm your Account just click this link:

<%= confirmation_url(@user.id, @user.confirmation_code, :host => "localhost:3000") %>

If you recieved this mail by mistake you are free to delete it.

Sincerly,
The Sample Blog Administration