config/routes.rb
Blog::Application.routes.draw do
  resources :users do
    resources :saved_posts, only: [:index]
    resources :friendships, only: [:index]
  end
  resources :blog_posts do
    resources :comments
  end
  
  resources :saved_posts, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  root :to => 'static_pages#home'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'
  match '/signup', to: 'users#new'
  match '/save/:blogpost_id', to: 'saved_posts#create', as: 'fav_blogpost'
  match '/delete/:blogpost_id', to: 'saved_posts#destroy', as: 'unfav_blogpost'
  match '/add_friend/:user_id', to: 'friendships#create', as: 'add_friend'
  match '/rm_friend/:user_id', to: 'friendships#destroy', as: 'remove_friend'
  match '/users/:user_id/confirm/:confirmation_code', to: 'users#confirmation', as: 'confirmation'
  match '/confirm_friendship/:friendship_id/:confirmation_code', to: 'friendships#confirmation', as: 'f_confirmation'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id, :other_friend_id
  
  belongs_to :friend, class_name: "User"
  belongs_to :other_friend, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = User.find_by_id(params[:user_id]).friendships
  end
  
  def create
    @friend = User.find(params[:user_id])
    current_user.befriend!(@friend)
    Notifier.friend_request(current_user, @friend).deliver
    
    
    
    redirect_to :back, notice: "Send a friend request to #{@friend.full_name}."
  end
  
  def destroy
    @friend = User.find(params[:user_id])
    current_user.unfriend!(@friend)
    redirect_to :back, notice: "Removed #{@friend.full_name} from your friendlist."
  end
  
  def confirmation
    friendship = Friendship.where(id: params[:friendship_id]).where(confirmation_code: params[:confirmation_code]).first
    reverse_friendship = Friendship.where(other_friend_id: friendship.friend_id).where(friend_id: friendship.other_friend_id).first
    
    unless !friendship == nil
      friendship.confirmed = true
      reverse_friendship.confirmed = true
      friendship.confirmation_code = nil
      reverse_friendship.confirmation_code = nil
            
      friendship.save
      reverse_friendship.save
      
      redirect_to user_friendships_path(current_user), notice: "Confirmed friend!"
    else 
      redirect_to root_path, alert: "Invalid page."
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend(friendship)
    User.find_by_id(friendship.other_friend_id)
  end
end

app/views/friendships/index.html.erb
<div class="center">
    <h1>Your friends</h1>
        <% if @friendships.any? %>
            <table class="test_friend">
                <tr class="friend_row">
                    <th colspan="2">User</th>
                    <th>Option</th>
                </tr>
    
                <% @friendships.each do |friendship| %>
                    <% if friendship.confirmed? %>
                    <tr class="friend_row">
                        
                        <div class="friend_details">
                        <% unless friend(friendship).image_url.nil? %>
                        <td><%= image_tag friend(friendship).image_url(:thumb).to_s %></td>
                        <% else %>
                        <td><%= image_tag("friendlist_default_avatar.jpg", alt: "Avatar") %></td>
                        <% end %>
                        <td class="friend_name">
                            <%= link_to friend(friendship).full_name, user_path(friend(friendship).id) %>
                            <br />                            
                            <%= render partial: 'friendship_partials/birthday',
                                 locals: { :friendship => friendship } %>
                        </td>
                        <span class="friend_option">
                        <td><%= link_to 'Remove', remove_friend_path(friend(friendship)),
                             class: "icon-remove"%></td>
                        </span>
                    </tr>
                    <% end %>
                <% end %>
            </table>    
        <% else %>
            <p>
                You have currently no friends.
            </p>
        <% end %>
</div>